## 张量拼接与切分

* 1.1 torch.cat()  
功能：将张量按维度dim进行拼接  
tensors:张量序列  
dim:要拼接的维度  

In [2]:
import torch

In [5]:
t1 = torch.ones((2,3))

In [6]:
t2 = torch.zeros((2,3))

In [8]:
torch.cat([t1,t2],dim=0)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.cat([t1,t2],dim=1)

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

In [13]:
torch.stack([t1,t2],dim=2).shape

torch.Size([2, 3, 2])

* torch.chunk()
功能：将张量按维度dim进行平均切分  
返回值：张量列表  
注意：不能整除，最后一份小于其他张量

In [19]:
  torch.chunk(t1,2)

(tensor([[1., 1., 1.]]), tensor([[1., 1., 1.]]))

## 张量的变换

* torch.reshape()
* input:
* shape

In [22]:
t = torch.randperm(8)

In [23]:
t

tensor([1, 7, 5, 4, 2, 3, 0, 6])

In [24]:
t_reshape = torch.reshape(t,(2,4))

In [26]:
t_reshape

tensor([[1, 7, 5, 4],
        [2, 3, 0, 6]])

In [28]:
t[0] = 2

In [29]:
t_reshape

tensor([[2, 7, 5, 4],
        [2, 3, 0, 6]])

* torch.transpose()
* input
* dim0:
* dim1:

torch.squeeze()
* 功能：压缩长度为1的维度

In [34]:
t = torch.rand((1,2,3,1))
t.shape

torch.Size([1, 2, 3, 1])

In [35]:
t_s = torch.squeeze(t)

In [36]:
t_s.shape

torch.Size([2, 3])

In [38]:
torch.squeeze(t,0).shape

torch.Size([2, 3, 1])

In [41]:
torch.unsqueeze(t_s,dim=0).shape

torch.Size([1, 2, 3])