## 张量简介

张量是一个多维数组  
张量的数据类型

In [4]:
import torch
import numpy as np

In [2]:
torch.FloatTensor,torch.cuda.FloatTensor

(torch.FloatTensor, torch.cuda.FloatTensor)

张量的形状（64,3,224,224）（b,c,w,h）

## 张量的创建

### 一、直接创建

torch.tensor()
功能：从data创建tensor  
* data:数据，可以是list，numpy  
* dtype:数据类型，默认与data的一致  
* device:所在设备，cuda/cpu 
* requires_grad:是否需要梯度
* pin_memory:是否存于索页内存

In [5]:
arr = np.ones((3,3))

In [7]:
arr,arr.dtype

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), dtype('float64'))

In [12]:
torch.tensor(arr)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

** 可以看到numpy和torch创建张量的数据类型是一样的  
.......................................................

* torch.from_numpy(ndarray)  
功能：从numpy创建tensor  
* 从torch.from_numpy创建的tensor于原ndarray共享内存，当修改其中一个的数据，另外一个也将会被改的

In [13]:
t = torch.from_numpy(arr)

In [14]:
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
arr[0,0] = 0

In [16]:
arr

array([[0., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
t

tensor([[0., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [18]:
t[0,0] = -1

In [19]:
t

tensor([[-1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [20]:
arr

array([[-1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

* 从上面可以看到他们是共享内存的，修改其中一个另一个就会被改

### 二依据数值创建

* 2.1 创建全0张量

torch.zeros()  
功能：根据size创建全0张量  
* size： 张量的形状，（3,3）（3,224,224）  
* out：输出的张量
* layout：内存中布局形式，有strided,sparse_coo等
* device:所在设备：cuda/cpu
* requires_grad:是否需要梯度

In [23]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
out_t =torch.tensor([1])

In [25]:
out_t

tensor([1])

In [26]:
torch.zeros((3,3),out=out_t)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [27]:
out_t

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

* 2.2 torch.zeros_like()
* 功能：依input形状创建全0张量
* input:创建与input同形状的全0张量
* dtype:数据类型
* layout:内存中的布局形式

In [30]:
input1 =torch.tensor(arr)

In [31]:
input1

tensor([[-1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [33]:
a = torch.zeros_like(input1,dtype=torch.float32)

In [34]:
a,a.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]), torch.float32)

同理 也有全1张量
* torch.ones()
* torch.ones_like()
功能：依input形状创建全一张量

In [35]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.ones_like(input1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

* torch.full()

In [38]:
torch.full((3,3),10)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])

In [39]:
torch.full_like(input1,5)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], dtype=torch.float64)

* torch.arange()

In [42]:
torch.arange(-1,1,0.5)#start,end,差值

tensor([-1.0000, -0.5000,  0.0000,  0.5000])

In [44]:
torch.linspace(-10,10,10)

tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])

In [47]:
torch.logspace(-10,10,10,1)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* torch.eye()
功能：创建单位对角矩阵（两维张量）  
注意事项：默认为方阵  
* n:行数
* m:矩阵列数

In [55]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## 三、依据概率分布创建张量

### 3.1torch.normal()

* 四种模式：  
 
 
  


mean为张量，std为张量

In [63]:
mean = torch.arange(1.,5.)
std = torch.arange(1,5,dtype=torch.float)

In [64]:
mean,std

(tensor([1., 2., 3., 4.]), tensor([1., 2., 3., 4.]))

In [65]:
torch.normal(mean,std)

tensor([ 1.4128,  7.1430,  7.3480, -2.5519])

mean为标量，std为标量

In [79]:
mean = 0.
std = 1.

In [84]:
torch.normal(0.,1.,size=(4,))

TypeError: normal() received an invalid combination of arguments - got (float, float, size=tuple), but expected one of:
 * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, torch.Generator generator, Tensor out)


mean为张量，std为标量

In [87]:
mean= torch.arange(1.,5.)
std = 1.

In [88]:
torch.normal(mean,std)

tensor([0.3856, 2.5143, 4.0019, 2.4352])

In [89]:
################

In [93]:
torch.randn((3,3))

tensor([[-0.3718,  1.0444, -0.3095],
        [ 0.8962,  0.2478, -1.1596],
        [-0.0432,  1.7633, -0.5670]])

In [98]:
torch.rand_like(input1)##在区间[0,1]上生成均匀分布

tensor([[0.9694, 0.1108, 0.4878],
        [0.7176, 0.4460, 0.4091],
        [0.7112, 0.8929, 0.1981]], dtype=torch.float64)

In [95]:
##均匀分布

In [104]:
torch.randint(-10,10,size=(20,))

tensor([  8, -10,  -5,  -8,   7,   4, -10,   5,  -8,   2, -10,  -1,  -4,  -8,
          1,  -2, -10,   9,  -8,   8])

torch.randperm()  
功能：生成从0到n-1的随机排列  
n:张量的长度

torch.bernoulli()
功能：依input为概率，生成伯努力分布（0,1分布，和亮点分布）